import { createUseStyles } from "react-jss";

// Type
interface StyleProps {
  sideBarIsActive: boolean;
}

export const useStyles = createUseStyles({
  root: {
    height: "100%",
    width: 280,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    backgroundColor: "var(--bg-paper, #ffffff)",
    color: "var(--text-primary, #0f172a)",
    transition: "0.25s",
    borderLeft: "1px solid var(--border-color, rgba(0, 0, 0, 0.08))",
    borderRight: "1px solid var(--border-color, rgba(0, 0, 0, 0.08))",
  },
  activeBar: {
    width: 280,
  },
  inactiveBar: {
    width: 72,
  },
  topPanel: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
  },
  logo: {
    width: 40,
    height: 40,
    cursor: "pointer",
  },
  navItems: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
    padding: "0 12px",
  },
  rightSideNavItems: {
    padding: "20px 16px !important",
  },
  subNavItems: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
    padding: 0,
    paddingLeft: 16,
  },
  navNoIconItem: {
    padding: "14px 16px !important",
    justifyContent: "space-between !important",
  },
  disableNavItem: {
    cursor: "default",
    "& $navText": {
      textDecorationLine: "line-through",
      color: "var(--text-disabled, #94a3b8)",
    },
  },
  childBadgeZero: {
    borderRadius: 100,
    backgroundColor: "var(--bg-surface, #f1f5f9)",
    color: "var(--text-secondary, #64748b)",
    fontSize: 12,
    borderColor: "transparent",
    fontWeight: 600,
  },
  childBadge: {
    borderRadius: 100,
    backgroundColor: "var(--bg-surface, #f1f5f9)",
    color: "var(--text-secondary, #64748b)",
    fontSize: 12,
    borderColor: "transparent",
    fontWeight: 600,
  },
  dot: {
    height: 7,
    width: 7,
    backgroundColor: "var(--primary-color, #0d6efd)",
    borderRadius: "50%",
    display: "inline-block",
    marginLeft: 5,
    marginBottom: 5,
  },
  badgeActive: {
    backgroundColor: "var(--primary-color, #0d6efd)",
    color: "#ffffff",
  },
  childBadgeAppoint: {
    borderRadius: 100,
    backgroundColor: "var(--bg-surface, #f1f5f9)",
    color: "var(--text-secondary, #64748b)",
    fontSize: 12,
    borderColor: "transparent",
    fontWeight: 600,
    height: 21,
    width: 29,
  },
  badgeActiveAppoint: {
    backgroundColor: "var(--primary-color, #0d6efd)",
    color: "#ffffff",
  },
  navActiveItem: ({ sideBarIsActive }: StyleProps) => ({
    padding: 12,
    minHeight: 48,
    backgroundColor: "var(--bg-surface-hover, rgba(0, 0, 0, 0.04))",
    justifyContent: sideBarIsActive ? "flex-start" : "center",
    alignItems: "center !important",
    display: "flex !important",
    flexDirection: "row",
    "& > svg, & > * > svg": {
      minHeight: 24,
      minWidth: 24,
    },
  }),
  navItem: ({ sideBarIsActive }: StyleProps) => ({
    padding: 12,
    minHeight: 48,
    justifyContent: sideBarIsActive ? "flex-start" : "center",
    alignItems: "center",
    display: "flex",
    flexDirection: "row",
    "& > svg, & > * > svg": {
      minHeight: 24,
      minWidth: 24,
    },
  }),
  linkBadge: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  childBadge2: {
    height: 20,
  },
  bottomPanel: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  welcomeText: {
    marginRight: 4,
    color: "var(--text-secondary, #64748b)",
  },
  userNameText: {
    display: "block",
    lineHeight: "20px",
    color: "var(--text-primary, #0f172a)",
    textAlign: "left",
    fontWeight: 600,
  },
  userInfoText: {
    display: "block",
    lineHeight: "20px",
    color: "var(--text-secondary, #64748b)",
    textAlign: "left",
  },
  menuArrowWrapper: {
    transform: "rotate(-90deg)",
    paddingRight: 5,
    position: "absolute",
    right: -2,
    "& svg path": {
      fill: "var(--text-secondary, #64748b)",
    },
  },
  userCard: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    padding: "20px 16px",
    position: "relative",
    backgroundColor: "var(--bg-paper, #ffffff)",
    color: "var(--text-primary, #0f172a)",
  },
  rightSideUserCard: {
    padding: "24px !important",
    maxHeight: 88,
  },
  borderTop: {
    borderTop: "1px solid var(--border-color, rgba(0, 0, 0, 0.08))",
    borderColor: "var(--border-color, rgba(0, 0, 0, 0.08))",
  },
  borderBottom: {
    borderBottom: "1px solid var(--border-color, rgba(0, 0, 0, 0.08))",
  },
  userWrapper: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 12,
    position: "relative",
  },
  menu: {
    padding: 0,
    width: "100%",
  },
  navActiveText: {
    color: "var(--primary-color, #0d6efd) !important",
  },
  navText: {
    color: "var(--text-primary, #0f172a)",
    whiteSpace: "break-spaces",
    fontWeight: 700,
    overflowX: "auto",
  },
  subNavText: {
    fontWeight: 500,
    color: "var(--text-secondary, #64748b)",
  },
  sideBarToggler: {
    height: 40,
    minWidth: 40,
    maxWidth: 40,
    borderRadius: 99,
    padding: "0px !important",
    border: "1px solid var(--border-color, rgba(0, 0, 0, 0.08))",
    color: "var(--text-primary, #0f172a)",
    backgroundColor: "var(--bg-surface, #f1f5f9)",
  },
  togglerIcon: {
    width: 24,
    height: 24,
  },
  sideBarActiveBtn: {
    minWidth: "40px !important",
    width: 40,
    height: 40,
    padding: "0px !important",
    "& > svg , & > * > svg": { padding: 0 },
  },
  logoAndTogglerWrapper: ({ sideBarIsActive }: StyleProps) => ({
    flexDirection: "row",
    display: "flex",
    alignItems: "center",
    justifyContent: sideBarIsActive ? "space-between" : "center",
    padding: "0 16px",
    height: 88,
  }),
  bottomNavItemWrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    position: "relative",
  },
  badge: {
    color: "var(--secondary-color, #0284c7)",
    backgroundColor: "var(--bg-surface, #f1f5f9)",
    height: 22,
    fontSize: 12,
    borderRadius: 99,
    paddingLeft: 8,
    paddingRight: 8,
    border: "none",
  },
  badgeText: {
    fontSize: 12,
    lineHeight: "20px",
    position: "absolute",
    color: "var(--secondary-color, #0284c7)",
    top: -12,
    right: -2,
  },
  textFieldsWrapper: {
    display: "flex",
    flexDirection: "column",
    padding: 24,
    paddingBottom: 23,
    gap: 16,
  },
  bottomNavItem: {
    color: "var(--text-secondary, #64748b)",
    position: "relative",
  },
  btn: {
    height: 40,
    minWidth: "40px !important",
    width: 40,
    background: "var(--bg-surface, #f1f5f9)",
    color: "var(--text-primary, #0f172a)",
    padding: 10,
    borderRadius: 5,
  },
});
