import { createUseStyles } from "react-jss";
import { ThemeInterface } from "../../interfaces/theme";
import { getComponentColors } from "../common/themes/color-grads";

export interface ComponentProps {}
const componentColors = getComponentColors();
export const useStylesFromThemeFunction = createUseStyles(
  (theme: ThemeInterface) => {
    return {
      tabs: {
        display: "flex",
        flexDirection: "column",
        width: "30px",
        height: "100%",
        position: "fixed",
        justifyContent: "flex-end",
        alignContent: "center",
        left: "0px",
        top: "0px",
        fontSize: "22px",
        fontFamily: "sans-serif",
        color: "var(--text-primary, #0f172a)",
        backgroundColor: "var(--bg-paper, #ffffff)",
        borderRight: "1px solid var(--border-color, rgba(0,0,0,0.08))",
      },
      tabsOnAuth: {
        width: "0px",
        height: "100%",
        position: "fixed",
        left: "0px",
        top: "0px",
      },
      tabsWithSidebar: {
        display: "flex",
        flexDirection: "column",
        width: "200px",
        height: "100%",
        position: "fixed",
        justifyContent: "flex-end",
        alignContent: "center",
        left: "0px",
        top: "0px",
        backgroundColor: "var(--bg-paper, #ffffff)",
        borderRight: "1px solid var(--border-color, rgba(0,0,0,0.08))",
        color: "var(--text-primary, #0f172a)",
      },
      tabsStyle: {
        display: "flex",
        flexDirection: "column",
        width: "200px",
        height: "100%",
        position: "fixed",
        justifyContent: "flex-start",
        alignContent: "center",
        left: "0px",
        top: "0px",
        fontSize: "22px",
        fontFamily: "sans-serif",
        backgroundColor: "var(--bg-paper, #ffffff)",
        color: "var(--text-primary, #0f172a)",
      },
      contentPanWithSidebar: {
        display: "flex",
        flexDirection: "column",
        marginLeft: "200px",
        height: "100vh",
        maxHeight: "100vh",
        overflowY: "auto",
        overflowX: "hidden",
        boxSizing: "border-box",
        backgroundColor: "var(--bg-default, #f8fafc)",
        color: "var(--text-primary, #0f172a)",
      },
      contentPan: {
        display: "flex",
        flexDirection: "column",
        marginLeft: "30px",
        height: "100vh",
        maxHeight: "100vh",
        overflowY: "auto",
        overflowX: "hidden",
        boxSizing: "border-box",
        backgroundColor: "var(--bg-default, #f8fafc)",
        color: "var(--text-primary, #0f172a)",
      },
      contentPanOnAuth: {
        marginLeft: "0px",
        height: "100vh",
        maxHeight: "100vh",
        overflowY: "auto",
        boxSizing: "border-box",
        backgroundColor: "var(--bg-default, #f8fafc)",
        color: "var(--text-primary, #0f172a)",
      },
      SidebarArrow: {
        position: "absolute",
      },
      link: {
        // textDecoration: "none",
        cursor: "pointer",
      },
      userIcon: {
        width: 30,
        height: 30,
      },
      menuLabel: {
        color: "var(--text-primary, #0f172a)",
      },
      profileMenuOption: {
        display: "flex",
        flexDirection: "row",
        gap: 8,
        justifyContent: "center",
        alignItems: "center",
      },
      profileTabWrapper: {
        display: "flex",
        flexDirection: "row",
        gap: 8,
        justifyContent: "start",
        alignItems: "center",
        color: "var(--text-primary, #0f172a)",
        fontSize: 20,
        fontWeight: 450,
        cursor: "pointer",
        paddingLeft: 5,
      },
      tabsContainer: {
        display: "flex",
        flexDirection: "column",
        height: "100vh",
        gap: 650,
      },
    };
  }
);
