name: Node.js CI with Docker

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Create build
        run: npm run build

      - name: Check Directories
        run: ls -al

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Path to the directory containing your Dockerfile
          push: true  # Set this to true to push the Docker image to a container registry

          # You can modify the image name as per your preference.
          # The example below assumes your repository name is "your-username/your-repo-name".
          # The final image will be named "your-username/your-repo-name:latest".
          # You can replace "your-username" and "your-repo-name" with appropriate names.
          tags: mhassaankhokhar/stella
      - name: Deploy
        uses: appleboy/scp-action@v1
        with:
          host: 146.190.4.216
          username: root
          password: ${{ secrets.COMPUTE_PASS }}
          port: 22
          source: ./deploy.sh
          target: /root
